# Generated by Django 5.1.5 on 2025-02-03 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
