# Generated by Django 5.1.5 on 2025-02-05 00:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shoe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
