# Generated by Django 5.1.5 on 2025-02-05 00:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shoe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dfhvvgzf2/image/upload/v1738714394/default_y0spv5.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
