# Generated by Django 5.1.5 on 2025-02-10 10:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dfhvvgzf2/image/upload/v1739183725/profile_xhxjdh.png', max_length=255, verbose_name='image'),
        ),
    ]
